from . import classnews_train
from . import classnews_test
from . import config
from . import classnews_score_test
from . import classnews_score_train
from . import LinearRegression_bj
from . import GaussianNB_iris
from . import logistic_train_iris
from . import kmeans
from . import svm_classnews